### ISSUE TITLE
Variable rowHeight for the whole gallery to be justified on both left and right?

### ISSUE THREAD

**Issue by Blkc** [benhowell/react-grid-gallery#10]
Right now it seems we are passing in a static number for the height of the row, but if there are images passed into the gallery with drastically different height and width, the row height is limited so the gallery rows are not completely filled from left to right. Note that I will have no control over the order of the images being passed in.
![screenshot from 2016-10-06 12-10-16](https://cloud.githubusercontent.com/assets/7827466/19160457/edb94244-8bbd-11e6-955f-648a0aab38df.png)

**Comment by Blkc** [comment]
I ended up incorporating [Flickr Justified Layout](https://github.com/flickr/justified-layout) for the position of the tiles.

**Comment by benhowell** [comment]
Thanks for the report @Blkc. I've only just returned from travelling so have only now seen your issue. Glad you could sort it out using the Flickr library (I'll look into it myself and may use it as the backend for react-grid-gallery one day).
