### ISSUE TITLE
Async image src loading

### ISSUE THREAD

**Issue by AlexChrisF** [benhowell/react-grid-gallery#102]
### Expected behaviour
I would like to load the image src from an asynchronous data source. For example loading image Base64 strings from an indexedDB database.
I don't want to make a copy and create an object of the whole database, in order to use the existing interface.

I imagine something like this:
```javascript
< Gallery images = {
    IMAGES
}
asyncLoadingFunction = {
    function myFunction(id, that)
    {
        databaseAPI.indexeddb.images.get(id).then(function (result)
        {
            if (result)
            {
                that._asyncRequest = null;
                that.setState(
                {
                    src: result.bytes
                });
            }
        });
    }
}
/>
```

**Comment by AlexChrisF** [comment]
Unfortunately the Lightbox interface would also needed to be changed

**Comment by benhowell** [comment]
Lightbox is supplied by the [react-images](https://github.com/jossmac/react-images) library.
