### ISSUE TITLE
Is there any example to make multiple galleries?

### ISSUE THREAD

**Issue by reotropi** [benhowell/react-grid-gallery#103]
Hi,
I'm trying to make multiple photo galleries separated by date, just like google photos. The images are dynamic from the server.
I tried calling Gallery repeatedly (in a loop) in render function like
```
<div>{date1}<Gallery id="0" images={this.state.photo[0]}........./><div><br />
<div>{date2}<Gallery id="1" images={this.state.photo[1]}........./><div><br />
```
But the photos are still not separated even though the gallery id are already different.
And the selection is also not available because the images selected are not passing which gallery id to the function.
Would you please give me a clue or example how to make it? Because your library is the most suitable for my project. Thanks a lot!

**Comment by benhowell** [comment]
Check out the [demo page](https://benhowell.github.io/react-grid-gallery/), it has multiple galleries. All the relevant code is [in the examples folder](https://github.com/benhowell/react-grid-gallery/tree/master/examples).

**Comment by reotropi** [comment]
Hi, just for the update (in case anyone want to make similar thing like I do), I have managed to make it by making rows n columns like 
```
<div className="row">
   <div className="col-sm-12">
      <Gallery id={String(i)} images={this.state.photos[i]} />
   </div>
</div>
```
And for the image, to know which gallery they belongs (for selecting), I put:
```
{ src: ....,
  thumbnail: ....,
  belongs: i,
  ...... };
```

So the gallery is also passed in function onSelectImage(index, image){}.
Maybe it's not the best approach but at least it is working for now.
Thanks a lot for your help :)
