### ISSUE TITLE
Override or namespace CSS class names to avoid conflicts

### ISSUE THREAD

**Issue by arel** [benhowell/react-grid-gallery#109]
### Expected behaviour
I would expect to be able to use the `Gallery` react component without CSS class names colliding with other classes in a project.

It would be nice to be able to either:
* override any class names used (e.g., passed in as a parameter to `Gallery`)
* or, namespace class names so they are less likely to conflict with other projects (such as with [BEM methodology](http://getbem.com/naming/))

### Actual behaviour

CSS class names such as `tile` conflict with the class names in the popular CSS framework, [bulma](https://bulma.io/). There doesn't seem to be a way to override the class names used by this framework.

### Steps to reproduce behaviour

The `tile` CSS class is used in `src/Image.js` and `lib/Image.js`. It is also used in https://bulma.io/documentation/layout/tiles/, making the two incompatible.

**Comment by benhowell** [comment]
Fixed in commit https://github.com/benhowell/react-grid-gallery/commit/c6eeef05a38fb26d6cf5ea2621997c842869915f
