### ISSUE TITLE
Feature request: auto orientation

### ISSUE THREAD

**Issue by TanLi233** [benhowell/react-grid-gallery#125]
Since you already have an orientation option on Image, it would be great if the component can automatically pick up orientation info from EXIF data from the image.
Right now almost all the images I use end up with wrong orientation in the browser, I find it hard to solve this elegantly while still using this great component. It will be much appreciated if you can add this feature.

**Comment by benhowell** [comment]
See: https://github.com/benhowell/react-grid-gallery/issues/66
