### ISSUE TITLE
row justification not working 

### ISSUE THREAD

**Issue by leovcunha** [benhowell/react-grid-gallery#126]
### Expected behaviour
Rows justified
### Actual behaviour
Rows not justified aligned to left
![image](https://user-images.githubusercontent.com/19495205/61412485-60565000-a8bf-11e9-9f56-4223b0437c07.png)

### Steps to reproduce behaviour
```
                    <Gallery
                        images={photographer.Photos.map(p => ({
                            src: p.cloudlink,
                            thumbnail: p.cloudlink
                        }))}
                        showLightboxThumbnails={true}

                    />
```

### Operating system
Win10
### Browser and version
Chrome 75.0.3770.100
### Hardware
Xeon 12-core

**Comment by benhowell** [comment]
thumbnailWidth and thumbnailHeight are required.
