### ISSUE TITLE
...need a little more details... 

### ISSUE THREAD

**Issue by minstrelMan** [benhowell/react-grid-gallery#13]
First off, thanks so much for sharing react-grid-gallery.  It's working quite nicely.

A few things have me wandering to and fro...
1.  shuffleArray - how and where is this defined.  When I remove it the gallery works fine; but the shuffle would be sweet.   note - I installed 'react-shuffle'; was not the solution.

2.  srcset - I'm currently trying a " lightboxImage:{src: '', srcset:[ ] " approach.  I can't get it working.
Please, could you give an example of the necessary setup for srcsets to work in react-grid-gallery.

Thanks again!

**Comment by benhowell** [comment]
Thanks!

1. shuffleArray is just a function I use to demonstrate the library. It's not part of the library, it's just something I threw on the demo page (hit "view page source" in your browser and you'll see it near the bottom). Anyway, this is it:

```js
function shuffleArray (array) {
  for (var i = array.length - 1; i > 0; i--) {
    var j = Math.floor(Math.random() * (i + 1));
    var temp = array[i];
    array[i] = array[j];
    array[j] = temp;
  }
  return array;
}
```

2. srcset support comes directly from the underlying library I use for the lightbox display called (react-images)[https://github.com/jossmac/react-images] by @jossmac. I haven't tested this myself as I've not needed it. 

Theoretically, this is how it would work in react-grid-gallery:

```jsx
images={[{
  src: 'http://example.com/example/img1.jpg',
  srcset: [
    'http://example.com/example/img1_1024.jpg 1024w',
    'http://example.com/example/img1_800.jpg 800w',
    'http://example.com/example/img1_500.jpg 500w',
    'http://example.com/example/img1_320.jpg 320w',
  ],
  thumbnail: 'http://example.com/example/thumbnailImg1.jpg',
  caption: "Image 1",
  thumbnailWidth: 180,
  thumbnailHeight: 320
},
{
  src: 'http://example.com/example/img2.jpg',
  srcset: [
    'http://example.com/example/img2_1024.jpg 1024w',
    'http://example.com/example/img2_800.jpg 800w',
    'http://example.com/example/img2_500.jpg 500w',
    'http://example.com/example/img2_320.jpg 320w',
  ],
  thumbnail: 'http://example.com/example/thumbnailImg2.jpg',
  caption: "Image 2",
  thumbnailWidth: 240,
  thumbnailHeight: 165
}
```

Read more about the srcset and sizes attributes here: [https://ericportis.com/posts/2014/srcset-sizes/](https://ericportis.com/posts/2014/srcset-sizes/).

**Comment by minstrelMan** [comment]
Excellent,
I'll give it all a go...!
Thanks for your detailed and incredibly fast response!
All Success!

**Comment by benhowell** [comment]
No worries :+1:

**Comment by am** [comment]
Hi @benhowell how can the `sizes` attr be set?

**Comment by benhowell** [comment]
srcset support comes directly from the underlying library I use for the lightbox display called react-images by @jossmac. I haven't tested this myself as I've not needed it.

Theoretically, this is how it would work in react-grid-gallery:

images={[{
  src: 'http://example.com/example/img1.jpg',
  srcset: [
    'http://example.com/example/img1_1024.jpg 1024w',
    'http://example.com/example/img1_800.jpg 800w',
    'http://example.com/example/img1_500.jpg 500w',
    'http://example.com/example/img1_320.jpg 320w',
  ],
  thumbnail: 'http://example.com/example/thumbnailImg1.jpg',
  caption: "Image 1",
  thumbnailWidth: 180,
  thumbnailHeight: 320
},
{
  src: 'http://example.com/example/img2.jpg',
  srcset: [
    'http://example.com/example/img2_1024.jpg 1024w',
    'http://example.com/example/img2_800.jpg 800w',
    'http://example.com/example/img2_500.jpg 500w',
    'http://example.com/example/img2_320.jpg 320w',
  ],
  thumbnail: 'http://example.com/example/thumbnailImg2.jpg',
  caption: "Image 2",
  thumbnailWidth: 240,
  thumbnailHeight: 165
}

Read more about the srcset and sizes attributes here: https://ericportis.com/posts/2014/srcset-sizes/.

**Comment by am** [comment]
Hi @benhowell , thank you for the reply. I'll raise the question there. About `srcset` it works as expected. The problem I see is that it hardcodes the `sizes` attribute and that doesn't make much sense. 

Cheers
