### ISSUE TITLE
change deprecated lifecycle hooks

### ISSUE THREAD

**Issue by mobji** [benhowell/react-grid-gallery#132]
### Expected behaviour
The image gallery should be working after react's 17.0 release.

### Actual behaviour
the Gallery and Lightbox components are using deprecated lifecycle hooks.

### Steps to reproduce behaviour
Using react-grid-gallery with lightbox anywhere in your application

**Comment by itoldya** [comment]
Hi @mobji! 

As [v0.5.6](https://github.com/benhowell/react-grid-gallery/releases/tag/v0.5.6) released we [no longer use](https://github.com/benhowell/react-grid-gallery/pull/174) `componentWillReceiveProps` hook in Gallery component. 

Lightbox is the part of [react-images](https://github.com/jossmac/react-images) library we use as a dependency. We are considering getting rid of lightbox functionality to fix your issue and be more agile in the future. Discussion on this topic is started [here](https://github.com/benhowell/react-grid-gallery/discussions/179). Please feel free to join.

**Comment by itoldya** [comment]
Lightbox was stripped out in the v1.0.0 so we do not use deprecated lifecycle hooks anymore
