### ISSUE TITLE
Completely breaks browser when switching to responsive mode.

### ISSUE THREAD

**Issue by IamFlowZ** [benhowell/react-grid-gallery#136]
### Expected behaviour
Application should adjust to the viewport.
### Actual behaviour
Application crashes the browser whenever the viewport is switched into Reactive Design mode.
### Steps to reproduce behaviour
Clone [my personal site](https://github.com/IamFlowZ/personal-site), checkout branch bug/react-gallery
### Operating system
Ubuntu 18.04 Kernel 4.15.0-72-generic
### Browser and version
* Firefox 74.0.1 
* Chromium 80.0.3987.163
### Hardware
i5 6600k GTX 1660ti

Could be related to: https://github.com/benhowell/react-grid-gallery/issues/132#issue-532560527

**Comment by itoldya** [comment]
Hi @IamFlowZ! Sorry for the very long reply.

Can you please clarify what did you mean by `switched into Reactive Design mode`? I checked out `bug/react-gallery` branch on your repo and everything seems to work fine for me. Thanks.

**Comment by itoldya** [comment]
Please feel free to reopen if the problem still exists
