### ISSUE TITLE
Selecting image by clicking the thumbnail?

### ISSUE THREAD

**Issue by robertfedus** [benhowell/react-grid-gallery#137]
Hello! I'm Robert and I'm using your React component from NPM in one of my projects. I actually want the images to act like buttons, and different things happening on different images. I can do this using the onSelectImage prop, but the problem is the function only gets triggered when the selection button is pressed. Instead, I only want it to trigger when I click the whole image, not only the selection button. So please, do you have any idea how this could be done? I would be extremely thankful. Thank you so much.

**Comment by itoldya** [comment]
Hi Robert! 

Prop `onClickThumbnail` is what you looking for.

```js
function App() {
  const handleClick = () => window.open("https://codesandbox.io/");

  return <Gallery onClickThumbnail={handleClick} images={images} />;
}
```
