### ISSUE TITLE
Open image via RIGHT click

### ISSUE THREAD

**Issue by Endriu12** [benhowell/react-grid-gallery#138]
How can I add functionality open on new tab& open in new window photo on the right click?

For ex. : I've the page with 20 photos and each of them I want to open in new window, but as photo detail page not just photo. The same for the: `Cntl + Click on photo`.  This should be the same behaviour as on onClickThumbnail method. 

Code :  
``` 
<Gallery  
              images={content}
              enableImageSelection={false}
              enableLightbox={false}
              rowHeight={220}
              margin={10}
              onClickThumbnail={(id) => this.openDetails(id)}
            />
```

**Comment by itoldya** [comment]
Hello @Endriu12!

You don't want to open lightbox you want thumbnails to act like ordinary links, right?

If so I suggest you use the `thumbnailImageComponent` prop to achieve this

```js
function ImageComponent(props) {
  return (
    <a href={props.item.href} target="_blank">
      <img {...props.imageProps} />
    </a>
  );
}

function App() {
  return (
    <Gallery
      thumbnailImageComponent={ImageComponent}
      images={images}
      enableImageSelection={false}
      enableLightbox={false}
    />
  );
}
```

Check out this [codesandbox](https://codesandbox.io/embed/thumbnailimagecomponent-usage-m461zj?fontsize=14&hidenavigation=1&theme=dark) for the fully functional example.

-----------

BTW, if you have a minute, please check out our [latest discussion](https://github.com/benhowell/react-grid-gallery/discussions/179) about the future of the project. We really appreciate your feedback! Have a good day!
