### ISSUE TITLE
Passing in className

### ISSUE THREAD

**Issue by brianrc** [benhowell/react-grid-gallery#14]
Is it possible to pass in a className for more find grained control over image layout?

Would like to adjust things to be more responsive.

**Comment by benhowell** [comment]
Hi Brian, I'm not sure what you mean (or more specifically what tags you would want to be placing your className on)?

You can style the gallery images yourself using css.
The general layout is such:
```html
<div class="tile">
  <div class="tile-icon-bar">
    <div title="Select"></div>
  </div>
  <div class="tile-bottom-bar"></div>
  <div class="tile-overlay"></div>
  <div class="tile-viewport">
    <img>
  </div>
</div>
```

**Comment by benhowell** [comment]
Closing this issue until some detail comes to light
