### ISSUE TITLE
Change select icon styles

### ISSUE THREAD

**Issue by ginioh** [benhowell/react-grid-gallery#141]
Hi, I'm struggling changing select icon styles. I would change the colors based on selection and this library also do this, but with images with white background, the icon letterally disappear.

Is there any workaround for this problem?

Thanks.

**Comment by steven-steven** [comment]
Same problem here. Wondering if there are plans to add this feature in (an extra style prop to customize the select icon)

**Comment by benhowell** [comment]
No plans to add this feature.
