### ISSUE TITLE
Setting thumbnail size to auto throws an error

### ISSUE THREAD

**Issue by Tugsbayar** [benhowell/react-grid-gallery#143]
### But, the following error occurred in my console.
`Failed prop type: Invalid prop `images[0].thumbnailHeight` of type `string` supplied to `Gallery`, expected `number`  in Gallery.`

### I assigned it as a string 'auto'. It worked as I expected. However, it printed out the error to my console.

My code
```
images.push({
	src: a.photo,
	thumbnail: a.photo,
	thumbnailWidth: 220,
	thumbnailHeight: 'auto',
	isSelected: a.chosen== 1 ? true : false,
	caption: "Photo"
});
```

**Comment by benhowell** [comment]
See: https://github.com/benhowell/react-grid-gallery#programmers-notes
