### ISSUE TITLE
Example of determining Thumbnail height and width

### ISSUE THREAD

**Issue by andy-hammond** [benhowell/react-grid-gallery#144]
The reference to a stackoverflow post to determine height and width of the thumbnail isn’t that clear. 

Can you provide us with an example in the wider context of this component being used?

Thanks in advance!

**Comment by aloukikomar** [comment]
i need this too,thanks

**Comment by umutsesen** [comment]
i need this too

**Comment by benhowell** [comment]
Links are given in readme. Read it.
