### ISSUE TITLE
is:issue is:open ould not find a declaration file for module 'react-grid-gallery'. '/Users/../../node_modules/react-grid-gallery/lib/Gallery.js' implicitly has an 'any' type.   Try `npm install @types/react-grid-gallery` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-grid-gallery';`ts(7016)

### ISSUE THREAD

**Issue by satyamkr571** [benhowell/react-grid-gallery#145]
![Screenshot 2020-07-14 at 9 09 43 AM](https://user-images.githubusercontent.com/47868971/87381242-dca67080-c5b1-11ea-94d5-2f9759f205a3.png)

**Comment by dschinkel** [comment]
I have the same error but using TypeScript.  You're not using TS and getting this?  that's weird

**Comment by darzang** [comment]
I'm having the same error without using Typescript.
I'm using Node 12.14.0 and react-grid-gallery@0.5.5 on Windows 10.

**Comment by hyouinKyouma** [comment]
@satyamkr571  any solutions?

**Comment by satyamkr571** [comment]
> @satyamkr571  any solutions?

I have created my own gallery for pictures I have not used this library

**Comment by itoldya** [comment]
Fixed in https://github.com/benhowell/react-grid-gallery/releases/tag/v0.5.6
