### ISSUE TITLE
Support for the gatsby

### ISSUE THREAD

**Issue by Bitha007** [benhowell/react-grid-gallery#148]
Gallery doesnot work properly in gatsby

**Comment by dev-ton** [comment]
It would be great, if gallery works with Gatsby Image

**Comment by layoutzweb** [comment]
I've been using it with Gatsby and SSR without much of a problem, try to not render the Gallery on the server side, either by using something like `gatsby-plugin-loadable-components-ssr`, and passing the ssr flag as false so it does not load on the server:
```javascript
import loadable from '@loadable/component'

const OtherComponent = loadable(() => import('./OtherComponent'), { ssr: false })
```

**Comment by benhowell** [comment]
Thanks @layoutzweb
