### ISSUE TITLE
Customizing the lightbox content

### ISSUE THREAD

**Issue by fydsa** [benhowell/react-grid-gallery#149]
Hi everybody,

I need to customize what is displayed when each image is clicked and lightbox is opened. Actually, I don't want to display the image in its original way and want to change the content and position of the image and caption which appears as footer. In other words, I want to show the caption alongside the image, not under the image; but I don't know how to do it. I really appreciate any help.

**Comment by itoldya** [comment]
Hi @fydsa 👋 

Lightbox content can be customized within the props [described here](https://github.com/benhowell/react-grid-gallery#lightbox-options). 

If you want to apply more customization you can look for another lightbox component package or create your own. 
To integrate the grid with your lightbox implementation you should use `onClickThumbnail` prop which fires after clicking on an image in the grid. 

Here is a very basic example

```js
function App() {
  const [currentImageIndex, setCurrentImageIndex] = React.useState(null);
  const currentImage = images[currentImageIndex];

  const handleClick = (index) => setCurrentImageIndex(index);

  const handleModalClose = () => setCurrentImageIndex(null);

  return (
    <>
      <Gallery onClickThumbnail={handleClick} images={images} />
      <Modal
        isOpen={!!currentImage}
        onClose={handleModalClose}
        image={currentImage}
      />
    </>
  );
}
```

Also, check out the fully functional [codesandbox example](https://codesandbox.io/embed/custom-lightbox-05n4jt?fontsize=14&hidenavigation=1&theme=dark) you can play with.

-----------

BTW, if you have a minute, please check out our [latest discussion](https://github.com/benhowell/react-grid-gallery/discussions/179) about the future of the product. We really appreciate your feedback! Have an awesome day!
