### ISSUE TITLE
Support for getting the position of the photo in a row

### ISSUE THREAD

**Issue by HariShankarS** [benhowell/react-grid-gallery#150]
Is there anyway I can get the position of the photo in a row, I mean if there are 10 photos rendered in a given row, on clicking the 6th photo can I know how many photos are present right to the given photo.
I'm trying to implement a custom design using this.
So, if you guys have any idea to solve my problem, it would be great. Thanks.

**Comment by itoldya** [comment]
Hi @HariShankarS!

Unfortunately, it's not possible at the moment but we want to provide users more flexibility in the next versions. You can read more about this in [this discussion](https://github.com/benhowell/react-grid-gallery/discussions/179).

Could you share more details about your use case? What exactly do you want to implement? It would be super helpful for our future development. Thanks!
