### ISSUE TITLE
Can we put text field custom control?

### ISSUE THREAD

**Issue by dbuldansjah** [benhowell/react-grid-gallery#155]
I have tried to add text input field on custom control, but the text field seems disabled, I can not make changes to the text field.

**Comment by itoldya** [comment]
Hi @dbuldansjah! 

Could you provide a code sample, sandbox link, or something for me to reproduce this behavior?

Here is a [codesandbox](https://codesandbox.io/embed/text-field-custom-control-h0x5sy?fontsize=14&hidenavigation=1&theme=dark) that demonstrates the usage of `customControls` prop where input there doesn't look disabled. I can assume that the problem in your case may be related to some global CSS, but I can't confirm it without seeing a reproducible sample.

Also, I want to notify you that future versions of the package will likely be shipped without lightbox functionality. Please check out [the discussion](https://github.com/benhowell/react-grid-gallery/discussions/179) to learn more.

**Comment by itoldya** [comment]
It's not actual now, because lightbox has been stripped out in the latest release.
