### ISSUE TITLE
On select image I don't see selected image is highlighted

### ISSUE THREAD

**Issue by swp44744** [benhowell/react-grid-gallery#16]
@benhowell - Thank you for the awesome utility. Everything works perfect but when I select an image it doesn't get highlighted as it does on demo. on select functions gets called and I could print index and image object on console though.
Below is the code I am using:

`onImageSelect(index, image) {`
`    console.log('Selected image',index, image)`
`}`

`<Gallery`
`images={IMAGES}`
`onSelectImage={this.onImageSelect}`
`enableImageSelection={true}`
`/>`

am I missing something? any help is appreciated. Thanks again.

**Comment by benhowell** [comment]
Image `isSelected` prop is stateless so you'll need to set that prop inside your `onImageSelect` function.
Take a look at the `onSelectImage` function in the code sample on the demo page: https://benhowell.github.io/react-grid-gallery/#code-sample

**Comment by swp44744** [comment]
Thanks ben I missed that example.. I will change my implementation... Appreciate your quick response.
