### ISSUE TITLE
context link per image

### ISSUE THREAD

**Issue by jojo05** [benhowell/react-grid-gallery#17]
Thank you for sharing react-grid-library. It's really useful!

Is there a way to include a link (or html) that is rendered when the image is open ? 

One idea would be to treat the caption as html and then I can link there to the image license or some additional page.

**Comment by benhowell** [comment]
Hi @jojo05 ,
The caption is an attribute of the image tag so can only be plain text unfortunately. 

One possible solution to your problem though, could be to use the customControls prop. 
More info here: https://github.com/jossmac/react-images/issues/58

**Comment by jojo05** [comment]
Yes, customControls prop would work. Any pointers to a simple example ?  (i.e. how do you add a simple link to customControls)

**Comment by benhowell** [comment]
There's an example here: https://github.com/jossmac/react-images/tree/master/examples/src/components/DownloadButton

**Comment by jojo05** [comment]
I use a wrapper similar to your main demo. Where would I specify the DownloadButton element ? 
Not obvious, sorry!

**Comment by jojo05** [comment]
I define a controls array with the control and I pass it as a fixed param <Gallery customControls={controls} /> and it renders, but what I mean is how to update the handler prop of the custom control for each image based on param in the images array ?

**Comment by jojo05** [comment]
My approach was to update the handler using onClickThumbnail, and accessing the element via a ref, but apparently a ref cannot be used for elements defined outside of the render method. Any alternative ideas?
Also, I think onClickThumbnail needs a bit more documentation. I assume the param is the images index which can then be accessed, but I still want the normal flow so maybe it should be another param like e.g. beforeOnClickThumbnail

**Comment by benhowell** [comment]
> I define a controls array with the control and I pass it as a fixed param and it renders, but what I mean is how to update the handler prop of the custom control for each image based on param in the images array ?

Not sure. This is a question for the https://github.com/jossmac/react-images library as that's what provides the underlying functionality in this instance.

> My approach was to update the handler using onClickThumbnail, and accessing the element via a ref, but apparently a ref cannot be used for elements defined outside of the render method. Any alternative ideas?

Yes, you can intercept the click with onClickThumbnail, capture the image index and do whatever and then call (or not) openLightbox. 

I'm not sure what you're getting at here, but I would be changing the customControls prop when the onClickThumbnail function is called. Don't know what element you mean but if it's the `<a href...>` element then you need to be passing that inside the customControls prop and manipulating it there. So thumbnail clicked -> change the element to whatever (the index will tell you which image has been clicked) -> beause the element has changed, the customControls prop will trigger a render as it's contents have changed.

https://github.com/jossmac/react-images/blob/master/examples/src/components/DownloadButton/index.js


> Also, I think onClickThumbnail needs a bit more documentation. I assume the param is the images index which can then be accessed, but I still want the normal flow so maybe it should be another param like e.g. beforeOnClickThumbnail

I don't understand what you're getting at here. Do you have a specific example?

**Comment by jojo05** [comment]
Below is a simple example using onClickThumbnail. It captures the image index but am not able to openLightbox.  What am I doing wrong?

[viewer.txt](https://github.com/benhowell/react-grid-gallery/files/723399/viewer.txt)

**Comment by jojo05** [comment]
I made it work by modifying your componentWillReceiveProps.
Maybe you know how to do it without this change !

`    componentWillReceiveProps (np) {
        [...]
        if (this.state.currentImage != np.currentImage) {
            this.setState({
                currentImage: np.currentImage
            });
        }
        if (this.state.lightboxIsOpen != np.isOpen) {
            this.setState({
                lightboxIsOpen: np.isOpen
            });
        }
    }
`

**Comment by benhowell** [comment]
Excellent! I'm glad you were able to come up with a solution ;-)

**Comment by jojo05** [comment]
That's a BUG in your code. Otherwise, how can you override onClickThumbnail?

**Comment by benhowell** [comment]
Pull requests are always welcome :)
