### ISSUE TITLE
Les't open GitHub Discussions

### ISSUE THREAD

**Issue by itoldya** [benhowell/react-grid-gallery#176]
Hi @benhowell! 

Can you open GitHub Discussions for this repo, please? I want to start a discussion about future versions of the librarty.

**Comment by benhowell** [comment]
Done!
I don't think there's a setting to allow only maintainers so it'll be
public.

**Comment by itoldya** [comment]
Nice! I have no hope that the discussion will attract a lot of people but I'm sure it must be public. Thank you!
