### ISSUE TITLE
Iframe CORS error

### ISSUE THREAD

**Issue by jjuli93** [benhowell/react-grid-gallery#182]
I've been sesing some CORS error on production coming from the iframe on the Gallery.js file only on safari and chrome IOS but could not reproduce the error locally. 
Does anyone else have a similar issue?

Inspecting the code i found that there is no src attribute on the iframe, reading about it on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-src) i think maybe the src attribute should be `about:blank`

### Expected behaviour
No CORS error

### Actual behaviour
![image](https://user-images.githubusercontent.com/11654462/187513592-9f0a6552-2fe6-4cd6-9a5b-8c114400e4a7.png)

### Operating system
IOS and macOS
### Browser and version
safari and chrome IOS

**Comment by itoldya** [comment]
Hi @jjuli93! Thanks for reporting! 

I couldn't reproduce the error, is it possible for you to give me access to your site or post a reproducible example?

`Iframe` is used here for gallery resize detection. I've been thinking of replacing it with an `object` tag, it should work the same way. But first, I want to confirm it doesn't have the same problem as iframe.

**Comment by itoldya** [comment]
since the v1.0.0 `iframe` is no longer used in the library
