### ISSUE TITLE
How to provide some UI feedback on click?

### ISSUE THREAD

**Issue by haschdl** [benhowell/react-grid-gallery#191]
This is just about user experience.

When clicking on a image, I get the feeling that there is some kind of visual feedback that something actually happened, or is about to happen. Since there is no visual identication of a click, it feels like the page is stuck, or that another click is needed. 
Have you noticed the same? Is there a  simple way to give some elegant clue that the click happened?
My site is live at [hscheidl.art](https://hscheidl.art) if you would like to check what I mean.

PS: I'm new to React and I'm reusing a template, so it might be that the behavior I described originates somewhere else - I was not able to find it though.

**Comment by itoldya** [comment]
Hello @haschdl! 

I've also noticed the lag after a click on your site. But I'm not sure we can do something on our side. Most probably it's a performance issue with your site. Page after the click is loading very slowly. I suggest you dig into the optimization of your components https://reactjs.org/docs/optimizing-performance.html.

**Comment by haschdl** [comment]
Thanks for the tips! Using `next/link` and fine-tuning the image loader had the biggest impact.
