### ISSUE TITLE
Max number of rows?

### ISSUE THREAD

**Issue by purplecones** [benhowell/react-grid-gallery#21]
Is there a way to or has anyone been able to set a max number of rows? I'd like to only show two rows regardless how many images I have.

**Comment by benhowell** [comment]
Hi,
There's currently no way to do this but it would be a simple option to add.
Basically, it'd require a new gallery prop like maxRows or something, and then use that prop to determine how many rows to build here: https://github.com/benhowell/react-grid-gallery/blob/master/src/Gallery.js#L202

**Comment by purplecones** [comment]
Thanks! I'll consider that. For now, I just set `overflow: hidden` with a set `height` on the parent div and it meets my requirement.

**Comment by benhowell** [comment]
No worries. It is a valid feature though, so I'm going to reopen this issue and try and knock something out now :+1:

**Comment by benhowell** [comment]
Released v0.3.2 containing optional `maxRows` prop. Enjoy!

**Comment by purplecones** [comment]
w00t! :-)
