### ISSUE TITLE
Getting undefined error while using in Sharepoint Framework  client side Webpart solution(React)

### ISSUE THREAD

**Issue by ArunPandianB** [benhowell/react-grid-gallery#23]
When i use <Gallery > tag in render i got the following error.

 Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. 

When i  go through the code i got ' this._gallery.clientWidth' as undefined. From where you are getting this props..
Thanks in advance..

**Comment by benhowell** [comment]
Hi,
`this._gallery` simply refers to the element of the mounted component and Element.clientWidth is a native js function. So if this is undefined then it suggests the component did not mount.

I'm not sure what you mean by "use tag in render", can you explain what you mean by that?
I have no idea what Sharepoint Framework client side webpart solution(React) is so I can't help you there. 

Can you paste a jsfiddle containing a test example?

**Comment by ArunPandianB** [comment]
I meant   <Gallery images={this.state.images}/> .

**Comment by ArunPandianB** [comment]
i meant using  " **<Gallery images={this.state.images} onSelectImage={this.onSelectImage}/>**"

**Comment by benhowell** [comment]
I'm having trouble understanding what your actual problem is. Can you paste a jsfiddle containing a test example?
