### ISSUE TITLE
Don't require thumbnail width & height

### ISSUE THREAD

**Issue by anhkhoi** [benhowell/react-grid-gallery#24]
Currently, thumbnail width and height properties are required. We can make them as non-required.
So, in this case, the js lib have to calculate the rate of width & height to show properly.
I'm require this feature, because in some cases we aren't know image width & height to set.

Warning on console

`Failed prop type: The prop `images[3].thumbnailWidth` is marked as required in `Gallery`, but its value is `undefined`.`
`NaN is an invalid value for the `width` css style property. Check the render method of Image.`

**Comment by benhowell** [comment]
Correct, `thumbnailWidth` and `thumbnailHeight` are required props. If need be, calculation of these values must be done outside the react-grid-gallery component. You can calculate these yourself as stated in the [README](https://github.com/benhowell/react-grid-gallery/blob/622531aef2f6443d03ab20a3e70a91d90d8a4380/README.md#general-notes)
