### ISSUE TITLE
React Deprecations in react-grid-gallery

### ISSUE THREAD

**Issue by forgo** [benhowell/react-grid-gallery#25]
Using the latest 0.3.3 version of react-grid-gallery:
```
warning.js?8a56:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
warning.js?8a56:36 Warning: A Component: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

I believe these issues might give you some guidance in removing the PropTypes warning:
[https://github.com/react-toolbox/react-toolbox/issues/1410](https://github.com/react-toolbox/react-toolbox/issues/1410)
[https://github.com/react-toolbox/react-toolbox/pull/1413](https://github.com/react-toolbox/react-toolbox/pull/1413)

And this may help with the deprecated React.createClass:
[https://github.com/reactjs/react-modal/issues/367](https://github.com/reactjs/react-modal/issues/367)

**Comment by benhowell** [comment]
[react-grid-gallery](https://github.com/benhowell/react-grid-gallery/) has been refactored for react 16.

React.createClass deprecation issue still remains as it's due to upstream package react-images, in particular, it's use of ReactCssTransitionGroup.

**Comment by forgo** [comment]
Cool, thanks for the info!

**Comment by ValYouW** [comment]
@benhowell Looks like react-images won't get a fix anytime soon:
https://github.com/jossmac/react-images/pull/134

Same holds for the "ScrollLock" modules (same author):
https://github.com/jossmac/react-scrolllock/issues/3

Maybe we should fork these 2 and start use the fork. What do you think?

**Comment by benhowell** [comment]
I think we should hold off until React 16. At this point we're just dealing with deprecation warnings. If, by the time React 16 is imminent and the upstream deprecations haven't been dealt with by @jossmac, I'll look at forking and patching  [react-images](https://github.com/jossmac/react-images).

**Comment by javivelasco** [comment]
Hi! Just wanted to let you know that react-toolbox is already released including full support for react 15.5. Sorry it took too long! :)

**Comment by benhowell** [comment]
Update: It seems https://github.com/jossmac/react-images/pull/134 has now been fixed and included in the latest release but https://github.com/jossmac/react-scrolllock/issues/3 is still pending.

[react-images](https://github.com/jossmac/react-images) releases are in a pretty messy state right now so I'm still holding off on updating until things settle down.

**Comment by benhowell** [comment]
All upstream dependencies have now been refactored for react 16. react-grid-gallery v0.3.5 includes these changes

**Comment by forgo** [comment]
Thanks for the update again!

Updating to v0.3.5 has removed the "propTypes" warning for me, but the one about "React.createClass" remains.

Any ideas on that?

**Comment by benhowell** [comment]
Sorry about that.
https://github.com/jossmac/react-images/issues/132 has been reopened.

This is due to upstream issue: https://github.com/jossmac/react-scrolllock/issues/3 still awaiting a fix to React.createClass deprecation.

Reopened.

**Comment by benhowell** [comment]
Closed by https://github.com/jossmac/react-scrolllock/pull/5
