### ISSUE TITLE
After re-render Gallery won't show new images until resize

### ISSUE THREAD

**Issue by kellenp** [benhowell/react-grid-gallery#26]
If I re-render a gallery with new image props, it doesn't show new images until I resize the window. I found that in componentDidUpdate it will not update the state unless the client has been resized - I'd recommend moving the thumbnail state update to its own function instead of onResize.

I'm not quite sure why componentDidUpdate only responds to resize, or I'd submit a PR.

https://github.com/benhowell/react-grid-gallery/blob/master/src/Gallery.js#L44

**Comment by benhowell** [comment]
I've just run a quick test and can't reproduce this bug.

Whenever your images array changes, `componentWillReceiveProps` is called and, if there is any change whatsoever (images, properties, whatever) the gallery thumbs are re-rendered. I can confirm that that is working here on the current release version.

Perhaps you can send me a fiddle that reproduces the problem.

**Comment by iMerica** [comment]
This is happening for me as well. I'm not even doing anything special. The gallery doesn't display at all until I resize the window.

**Comment by benhowell** [comment]
Can send me a fiddle that reproduces the problem? Thanks.

**Comment by dmytro-shchurov** [comment]
For me this also doesn't work when a Panel which contains the gallery is rendered as (by simplifying)
```
<Panel>
    {React.Children.map(... <Fade><Panel>{child_component_with_the_gallery */}</Panel></Fade>)}
</Panel>
```
inside a "wizard" component

**Comment by benhowell** [comment]
@dmytro-shchurov Do you mean the images don't render?
