### ISSUE TITLE
Please consider supporting the react-images showThumbnails property

### ISSUE THREAD

**Issue by markhepburn** [benhowell/react-grid-gallery#28]
The underlying [react-images](http://jossmac.github.io/react-images/) Lightbox component has a nice option `showThumbnails`, which draws a strip of images from the gallery along the bottom.

Please consider adding this to your Gallery Lightbox options.

**Comment by benhowell** [comment]
Included in v0.3.6. See [CHANGELOG](https://github.com/benhowell/react-grid-gallery/blob/1f956536ec7a829a8ef2c0334ac55f96048f6499/CHANGELOG.md). Enjoy!

**Comment by markhepburn** [comment]
Thanks!
