### ISSUE TITLE
Update Lib Files

### ISSUE THREAD

**Issue by ambaum2** [benhowell/react-grid-gallery#32]
I may be doing things wrong, but could you run node gulpfile.js and commit? 

The constructors for Gallery.js and CheckButton.js break on IE 10 and lower. But running node gulpfile to update the lib files and then installing locally fixes my app. thanks

**Comment by benhowell** [comment]
Hi,
The files under src/ aren't intended to be used in their raw form. These files are written in ES6 and are transpiled to ES5 using babelify task via gulp. 

gulpfile.js is always run as a part of the build process so the files in lib/ are the result of running gulp.

The easiest way to install [react-grid-gallery](https://github.com/benhowell/react-grid-gallery) is via npm as stated in the README. Alternatively, you can download/clone the repo and run gulp yourself (which it appears you are already doing).

Finally, I don't intend to support anything prior to IE 11 so I will update the docs to reflect that.

Thanks.
