### ISSUE TITLE
overflow-y hidden to the body

### ISSUE THREAD

**Issue by mustafawm** [benhowell/react-grid-gallery#34]
Hi,

Thanks for the awesome library!

I'm trying to implement the gird gallery so that when I click on a button, the lightbox will be displayed immediately `isOpen={true}`

I noticed the lightbox adds css rule: `overflow-y:hidden` to the body tag, which is fine except it's not removing that css rule when I close the lightbox (press `esc`) causing the page to freeze (no scroll)!

Any ideas/suggestions on how to workaround this?

**Comment by benhowell** [comment]
Hi,
This is a bug in upstream package https://github.com/jossmac/react-images
This is the issue in question.
https://github.com/jossmac/react-images/issues/146

I will push an update when this is fixed upstream.

**Comment by mustafawm** [comment]
Thanks for your timely response.

If anyone else having the same issue, my current workaround is reseting those rules by adding the below line to the `lightboxWillClose` life-cycle method  

```
Object.assign(document.body.style, {paddingRight: 0, overflowY: 'auto'}) 
```

>Check your original body tag css rules (padding-right & overflow-y) and reset to those.

**Comment by benhowell** [comment]
Thanks for the workaround example... hopefully it'll be of use to others.
I'll leave this issue open until things are fixed upstream :+1:

**Comment by benhowell** [comment]
https://github.com/jossmac/react-images/issues/146 closed
