### ISSUE TITLE
Allow click on overlay

### ISSUE THREAD

**Issue by dreson4** [benhowell/react-grid-gallery#38]
It would be nice to allow to click on overlay, I've seen in your code the pointer events are all set to none. I tried to add onClick to my overlay but they get overwritten by the parent div in your source code. 

Its possible for someone to add buttons onHover which do different functions to the image, it would be really nice if they are clickable.

Thanks for a good gallery.

**Comment by benhowell** [comment]
Pointer events are set to `none` when using the `customOverlay` prop to allow the click event to target the image underneath the overlay. Overlays, being custom, can completely obscure the image underneath and as such pointer events have been disabled for the overlay.

You make a valid point though. Have you tried explicitly setting pointer events to `auto` on your buttons?

**Comment by dreson4** [comment]
I tried but it didn't work. For some reason the click still passes through to the image.

I set up my overlay like this 
`image.customOverlay=(
          <div style={styles.thumbOverlayContainer}>
            <p onClick={this.overlayOnCreate}>Set as cover image</p>
            <p onClick={this.overlayOnDelete}>Delete</p>
          </div>`

It doesn't work though, I'm sure the methods and 'this' work fine because I called them from within the same function and they work.
So I decided to look into your code and change some things, in Image.js

`var customOverlay = (typeof this.props.item.customOverlay === 'undefined')
                ? <noscript/> :
                <div style={{
                    pointerEvents: "none",
                    opacity: this.state.hover ? 1 : 0,
                    position: "absolute",
                    height: "100%",
                    width: "100%"}}>
                {this.props.item.customOverlay}
            </div>;`

I tried changing pointerEvents to auto didn't work, removed that line altogether didn't work. 

Then in return method I thought let me change the position of {customOverlay} because it was in the middle, I put it as the first element on the div, also as the last but none of them worked, tried zIndex as well maybe to see if it could work. I have no idea whats preventing the click from being detected. 

I also did e.stopPropagation() in my onClick methods just to see if maybe it was because of that the click was passing through but nothing. 

At this point I have no idea what else to change.

**Comment by benhowell** [comment]
Did you try setting `pointerEvents: "auto"` in your `onClick` elements like below?
```jsx
<p onClick={this.overlayOnCreate} style={{pointerEvents: "auto"}}>Set as cover image</p>
```

**Comment by dreson4** [comment]
That one worked.
Thanks a lot.

**Comment by HRNPH** [comment]
hmm the overlay click is still disabled by default right?
