### ISSUE TITLE
Dependency Issues using this with react-native

### ISSUE THREAD

**Issue by thatchej** [benhowell/react-grid-gallery#39]
Hey there, I'm trying to work on including this into my project, but using the simple example I get some serious dependency issues that I can't quite work out. 

When I first install this lib, it complains about being unable to resolve module 'react-dom'. All well and good, I'll install react-dom at the wanted version, but then 'react-dom' starts throwing errors about not being about to resolve module 'react/lib/React' -- I'm thinking something is fundamentally wrong.

![img_0492](https://user-images.githubusercontent.com/1555889/30191735-bd557a76-93f7-11e7-9424-1e818abd9d1c.PNG)
![img_0493](https://user-images.githubusercontent.com/1555889/30191736-bd570486-93f7-11e7-851f-c3cfe63ae2cf.PNG)

Have you ran into anything like this? Would really love to use this library.

**Comment by thatchej** [comment]
I'm realizing that I think this is an issue of me not understanding how React Native differs from React in terms of the DOM. I don't think this component will ever work.

I'll close this issue, but thanks for making an awesome component! I'll use it if I ever have the use case for a web app.

**Comment by benhowell** [comment]
Hi @thatchej , unfortunately I don't know the first thing about react native so I have nothing to suggest. Thanks for the compliment and I hope you get your dependency issues sorted.
