### ISSUE TITLE
RangeError: Maximum Call Stack size Exceeded

### ISSUE THREAD

**Issue by AhsanT4riq** [benhowell/react-grid-gallery#41]
When updating images from state to Gallery component, i am getting a console error of RangeError: Maximum call stack size exceeded. Images are rendered correctly but getting the following error.

Uncaught RangeError: Maximum call stack size exceeded
    at trackProperties (trackForMutations.js?7bd4:16)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)
    at trackProperties (trackForMutations.js?7bd4:32)

**Comment by AhsanT4riq** [comment]
class CompanyLogo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      images: []
    };
    this.logoStep = 0;
  }

// Updating logoimage from nextprops

  componentWillReceiveProps(nextProps) {
    if (nextProps.logoImage.length) {
      this.setState({ images: nextProps.logoImage });
    }
  }
  handleChange = e => {
    let file = {};
    file = e.target.files[0];
    const fileForLogoValidation = {
      salonLogo: file
    };
    let res = checkLogoFile(fileForLogoValidation);
    if (!res.isError) {
      this.props.addLogo({
        companyId: this.props.companyId,
        auth: this.props.auth,
        fileObject: file
      });
    }
    this.props.handleChange(file, this.logoStep);
  };
  onSelectImage = index => {
    let images = this.state.images.slice();
    let img = images[index];
    if (img.hasOwnProperty("isSelected")) img.isSelected = !img.isSelected;
    else img.isSelected = true;
    this.setState({ imagas: images });
  };
  render() {
    const { errors } = this.props;
    const images = this.state.images.map(i => {
      i.customOverlay = (
        <div style={styles.captionStyle}>
          <div>{i.caption}</div>
        </div>
      );
      return i;
    });
    return (
      <Col xs={12}>
        <FormGroup
          controlId="salonLogo"
          validationState={errors.salonLogo ? "error" : null}
        >
          <RaisedButton
            primary={true}
            label="Logo Image"
            labelPosition="before"
            containerElement="label"
            style={{ margin: 2 }}
          >
            <input
              type="file"
              style={styles.exampleImageInput}
              id="salonLogo"
              accept="image/png,image/bmp,image/jpeg"
              onChange={this.handleChange}
              onFocus={this.props.clearErrors}
            />
          </RaisedButton>
          {errors.salonLogo ? <HelpBlock>{errors.salonLogo}</HelpBlock> : null}
        </FormGroup>

// passing images in Gallery components

        <Gallery
          showLightboxThumbnails={true}
          onSelectImage={this.onSelectImage}
          images={images}
          enableImageSelection={false}
        />
      </Col>
    );
  }
}

**Comment by benhowell** [comment]
Looks like you've got some runaway process going on in your code (endless recursion). The files listed in the error message is the place to start looking.

**Comment by giorgim** [comment]
@benhowell we also experienced max call stack exceeded error with this component, more precisely when we rendered _two_ Gallery components on the same page, it would result in max call stack exceeded error sometimes; for the same images/files, when we rendered only  a single gallery, this error dissappeared.
