### ISSUE TITLE
Clickable Customoverlay

### ISSUE THREAD

**Issue by kingarawana** [benhowell/react-grid-gallery#44]
When I add a customOverlay with an HTML element with an onClick handler, it doesn't fire when I click on the custom overlay element.

Example:
`
[{
        src: "https://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg",
        thumbnail: "https://www.html5rocks.com/en/tutorials/speed/img-compression/len_std.jpg",
        thumbnailWidth: 100,
        thumbnailHeight: 100,
        customOverlay: (<button style={{zIndex: 10000}} onClick={()=>{alert('hello!')}}>hello world</button>)
}]
`
When I hover over the thumbnail, the button is visible as expected. But when I click on it the alert never shows and the lightbox shoes instead.

I also using onClickThumbnail to inspect the target to see if I can tell when the button was clicked, but that also doesn't work. The target is always the image tag.

Please let me know what the correct approach is. My goal is to add "delete" button where the user can click an X button to delete the image.

Thanks!

**Comment by benhowell** [comment]
You shouldn't be wrapping your button in parentheses.
