### ISSUE TITLE
negative margin-left brokes a grid

### ISSUE THREAD

**Issue by nekifirus** [benhowell/react-grid-gallery#45]
Sometimes images look very strange. Can I do anything with it?

[screen](http://tinypic.com/r/33y6yow/9) 
Look at top left image. It props

```
marginLeft: -26
scaletwidth:101
src:"https://pp.userapi.com/c621830/v621830842/2a79a/D5bk9J7tk4s.jpg"
srcset:undefined
thumbnail:"https://pp.userapi.com/c621830/v621830842/2a797/KjtXLuTOrc0.jpg"
thumbnailHeight:604
thumbnailWidth:340
vwidth:49

```

Props for top right image

```
marginLeft:-257
scaletwidth:1055
src:"https://pp.userapi.com/c621830/v621830842/2a7ae/QsEpr5qTB_M.jpg"
thumbnail:"https://pp.userapi.com/c621830/v621830842/2a7ab/jEDe8cKl3p0.jpg"
thumbnailHeight:103
thumbnailWidth:604
vwidth:540
```

**Comment by nekifirus** [comment]
[screen](http://tinypic.com/r/2csdhdv/9)

Look at this screen too, please.

**Comment by benhowell** [comment]
Can you paste your images array because I can't understand what's happening
here. Have you got a live demo I can look at?

**Comment by nekifirus** [comment]
I can't gave a demo, because photos takes from russian social network VK.com. After receive it from VK, I'm prepare it and have this image array:
`[{"src":"https://pp.userapi.com/c303713/v303713282/37b/ga5eCTErEDs.jpg","thumbnail":"https://pp.userapi.com/c303713/v303713282/378/DBgSuE8W0h4.jpg","id":283319956,"owner_id":100282,"thumbnailHeight":480,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c304700/v304700082/1d76/-CW9ICTYEcw.jpg","thumbnail":"https://pp.userapi.com/c304700/v304700082/1d74/HJRYUAI45RM.jpg","id":285549050,"owner_id":14710082,"thumbnailHeight":435,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c637722/v637722982/4ca99/z-ugVAjz4xk.jpg","thumbnail":"https://pp.userapi.com/c637722/v637722982/4ca99/z-ugVAjz4xk.jpg","id":456240253,"owner_id":12968982,"thumbnailHeight":500,"thumbnailWidth":600},{"src":"https://sun9-14.userapi.com/c639726/v639726842/20b42/XnR7-1RyICc.jpg","thumbnail":"https://sun9-14.userapi.com/c639726/v639726842/20b40/DTjO4cHqKhY.jpg","id":456239098,"owner_id":5445842,"thumbnailHeight":604,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c836534/v836534345/18fa9/GVV0o_B7Pnc.jpg","thumbnail":"https://pp.userapi.com/c836534/v836534345/18fa7/teuVY3RDqMk.jpg","id":456239087,"owner_id":16864345,"thumbnailHeight":604,"thumbnailWidth":427},{"src":"https://pp.userapi.com/c836125/v836125247/32d09/ezbnGcPVSHw.jpg","thumbnail":"https://pp.userapi.com/c836125/v836125247/32d07/8E-C3WDnUPE.jpg","id":456239835,"owner_id":5889247,"thumbnailHeight":567,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c604816/v604816842/3c1d0/pcoe-wkvRDk.jpg","thumbnail":"https://pp.userapi.com/c604816/v604816842/3c1ce/321u76QgeCQ.jpg","id":456239079,"owner_id":5445842,"thumbnailHeight":604,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c836137/v836137247/123b/1_-vFfMfPfQ.jpg","thumbnail":"https://pp.userapi.com/c836137/v836137247/1238/XgfQ71xc3z0.jpg","id":429115571,"owner_id":5889247,"thumbnailHeight":362,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c636021/v636021446/6643a/KQiCXRlBbsw.jpg","thumbnail":"https://pp.userapi.com/c636021/v636021446/66437/qMELCYdgwz4.jpg","id":435564390,"owner_id":5602596,"thumbnailHeight":453,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c626620/v626620638/27329/3r7zQVZoVps.jpg","thumbnail":"https://pp.userapi.com/c626620/v626620638/27327/rogFcYlq7-8.jpg","id":428753463,"owner_id":-97357221,"thumbnailHeight":374,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c631724/v631724842/45451/esi48V577PU.jpg","thumbnail":"https://pp.userapi.com/c631724/v631724842/4544f/NsJCCrcRoB0.jpg","id":433446695,"owner_id":5445842,"thumbnailHeight":604,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c631724/v631724842/4545a/jXN0P_rjuRg.jpg","thumbnail":"https://pp.userapi.com/c631724/v631724842/45458/3dfKy8Tooio.jpg","id":433446857,"owner_id":5445842,"thumbnailHeight":604,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c631724/v631724842/4546c/xD2HtYLayNA.jpg","thumbnail":"https://pp.userapi.com/c631724/v631724842/4546a/xMTZgeCraHU.jpg","id":433447150,"owner_id":5445842,"thumbnailHeight":604,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c631724/v631724842/45474/hAzqjpIsmiw.jpg","thumbnail":"https://pp.userapi.com/c631724/v631724842/45473/SHuCW23cPKU.jpg","id":433447674,"owner_id":5445842,"thumbnailHeight":604,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c630723/v630723912/4b870/sJOZocp9X4c.jpg","thumbnail":"https://pp.userapi.com/c630723/v630723912/4b86d/zH3MpnQAyXA.jpg","id":428941663,"owner_id":13839334,"thumbnailHeight":373,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c604330/v604330593/18cf8/0ZPPUPl51gY.jpg","thumbnail":"https://pp.userapi.com/c604330/v604330593/18cf6/iI-GkK8CjWI.jpg","id":424495705,"owner_id":-119719115,"thumbnailHeight":453,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c631529/v631529345/3d11e/DqRFUhCt3k4.jpg","thumbnail":"https://pp.userapi.com/c631529/v631529345/3d11b/A_n5yh95C2g.jpg","id":424854200,"owner_id":1518656,"thumbnailHeight":406,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c631529/v631529345/3d11e/DqRFUhCt3k4.jpg","thumbnail":"https://pp.userapi.com/c631529/v631529345/3d11b/A_n5yh95C2g.jpg","id":424105723,"owner_id":16864345,"thumbnailHeight":406,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c630416/v630416282/35c0b/YpGOFvc5TPA.jpg","thumbnail":"https://pp.userapi.com/c630416/v630416282/35c08/ZgiG64pDsaM.jpg","id":418797085,"owner_id":100282,"thumbnailHeight":403,"thumbnailWidth":604},{"src":"https://pp.userapi.com/c630416/v630416282/35c97/2wCkPpHrWTo.jpg","thumbnail":"https://pp.userapi.com/c630416/v630416282/35c94/QBQFGIxhRYg.jpg","id":418798379,"owner_id":100282,"thumbnailHeight":403,"thumbnailWidth":604}]
`

**Comment by benhowell** [comment]
Your array is formatted as JSON and I'm not sure how it even works in the
first place! The keys shouldn't be stringy.

**Comment by nekifirus** [comment]
I need to change "thumbnailWidth":604 to "thumbnailWidth":"604"?

**Comment by benhowell** [comment]
C'mon mate, take a look at the quick start guide:
https://github.com/benhowell/react-grid-gallery#quick-and-dirty-start

**Comment by nekifirus** [comment]
Array in props [look it](http://tinypic.com/r/2vjx3zd/9)

**Comment by benhowell** [comment]
I tested using a non-stringy key version of your array and the results were fine so your problem must be outside of react-grid-gallery. You need to look elsewhere in your code.

![untitled](https://user-images.githubusercontent.com/1784519/31053557-d60ee6fe-a6eb-11e7-9c1f-b55a9b7be1d2.png)

**Comment by nekifirus** [comment]
And my page. Maybe it working for you, because gallery takes full page?
[IMG]http://i67.tinypic.com/2q05xqo.png[/IMG]

**Comment by nekifirus** [comment]
https://github.com/benhowell/react-grid-gallery/blob/master/src/Gallery.js#L53

**Comment by nekifirus** [comment]
Hello! I'm solve a problem.

In my global css I have a style 
`img 
  { max-width:100%;}`

With this stile your crop method with margin-left don't working. I'm add style to <img> in gallery
`img{
  max-width: none;
}
`

And all work fine! I'm happy.


But I think you need to add in your product

> max-width: none;

because many css frameworks as bootstrap set max-width:100% as default and your crop method maybe don't working for many people. 

Thank you, for your Gallery.

**Comment by benhowell** [comment]
That's interesting. I use bootstrap and have never come across this problem. However, I don't think it's viable, or the components responsibility to try to predict the nuances of third party css frameworks. The correct approach in this case is the one you've taken.

Thanks for the update :+1:

**Comment by nekifirus** [comment]
Yesterday I find another way. It works with `img { max-width:100%;}`
Remove margin-left to resize image https://github.com/benhowell/react-grid-gallery/blob/master/src/Gallery.js#L186
And add style `img{object-fit: cover;}` to image.
