### ISSUE TITLE
Thumbnails being Forced to viewport size.  I want them to show actual size.

### ISSUE THREAD

**Issue by dschinkel** [benhowell/react-grid-gallery#46]
For some reason the images are defaulting to 271x180 even though the image was clearly set to 117x77, it still filled 271x180:

companies.json
```
 "misc": {
        "enabled": true,
        "list": [
          {
            "src": "/lib/assets/xpeppers/company/xpeppers-iteration-planning.jpg",
            "thumbnail": "/lib/assets/xpeppers/company/xpeppers-iteration-planning-thumb.jpg",
            "thumbnailWidth": 116,
            "thumbnailHeight": 77
          }

        ]
      }
```

<img width="1112" alt="screen shot 2017-10-11 at 1 06 20 am" src="https://user-images.githubusercontent.com/338798/31424559-816d987a-ae20-11e7-9b1c-aa51876ac7de.png">

I hacked it manually in Chome Dev tools...and this shows how It should have shown up based on 117x77:

<img width="1063" alt="screen shot 2017-10-11 at 12 52 56 am" src="https://user-images.githubusercontent.com/338798/31424207-9a37f46a-ae1e-11e7-99d2-afe164728563.png">
<img width="560" alt="screen shot 2017-10-11 at 12 53 12 am" src="https://user-images.githubusercontent.com/338798/31424208-9c124c7c-ae1e-11e7-96d7-b4c913a6950e.png">

**The code that calls it**

`<ImageGallery  images={company.images.misc.list} />`

**ImageGallery.js**
```
import React, { Component } from 'react';
import Gallery from 'react-grid-gallery';

export default class ImageGallery extends React.Component {
  render() {
    return (
      <Gallery images={this.props.images} />
    )
  }
}

```

You can see here the viewport is not tight to the image width and height.  And again I want these thumbs to show smaller

<img width="1225" alt="screen shot 2017-10-11 at 1 29 33 am" src="https://user-images.githubusercontent.com/338798/31425188-c6dfa9fe-ae23-11e7-9b91-e7d1bfdb8c72.png">

So how can I get this to work, why is the viewport size overriding my thumbnailWidth and thumbnailHeight?

**Comment by benhowell** [comment]
Hi @dschinkel, 
The default row height is 180px. thumbnailHeight and thumbnailWidth should be the real values of the actual thumbnail (this is so the library can scale the images and keep aspect ratio, etc.).

If, for example, you want the thumbnails to be 77px, you need to set that as a gallery option (rowHeight): https://github.com/benhowell/react-grid-gallery#gallery-options

As this is a grid gallery, all thumbnail images are scaled to the value of rowHeight.
