### ISSUE TITLE
Not working with Preact

### ISSUE THREAD

**Issue by diazweb** [benhowell/react-grid-gallery#49]
Hello everybody,

I'm getting this error in a project with Preact activated.

![screen shot 2017-11-02 at 12 39 12](https://user-images.githubusercontent.com/4911113/32324295-37e17dfe-bfcb-11e7-8485-472d41a5b03e.png)

Does someone have any clue about this?

Thanks,

**Comment by benhowell** [comment]
Hi @diazweb, I have only developed [react-grid-gallery](https://github.com/benhowell/react-grid-gallery) with react in mind and therefore haven't even looked at preact. If, by coincidence, preact is compatible as a drop in replacement for react then great, but I have no plans on specifically testing/developing with preact in mind.

As this is not an issue with [react-grid-gallery](https://github.com/benhowell/react-grid-gallery) itself, I'm closing the issue.
