### ISSUE TITLE
Incompatible with Server Rendering (Server rendering: "document is not defined")

### ISSUE THREAD

**Issue by AlexandreKilian** [benhowell/react-grid-gallery#5]
This component is unfortunately unusable when using server rendering since it's accessing the document without checking if the DOM is available first

**Comment by benhowell** [comment]
Hi,
Can you post your stack trace? I don't think I've referred to the DOM anywhere other than in the example apps. 

The only other thing that comes to mind is if you're rendering your app without checking for the existence of DOM. 
e.g.
```jsx
if(typeof window !== 'undefined') {
    ReactDOM.render(<Demo1 />, document.getElementById('demo1'));
}
```
Anyway, post your stacktrace and I'll take a look.

**Comment by AlexandreKilian** [comment]
that is indeed weird, I checked the code and can't find out why this is happening ôO... every occurence is properly escaped....
I can't get a proper stacktrace due to the server rendering module I'm using atm, I'll have to check it myself

**Comment by benhowell** [comment]
No worries. I'll close the issue unless and until something turns up.
