### ISSUE TITLE
Lazy Loading Images

### ISSUE THREAD

**Issue by steverob** [benhowell/react-grid-gallery#50]
Hi is it possible to load actual images lazily when they're visible in the viewport?

Thanks.

**Comment by benhowell** [comment]
Hi, I'm not quite sure what you mean. Once the images are visible in the viewport (by which I assume you mean thumbnail viewports), they've already been loaded and hence why they're visible.

Lightbox images are loaded lazily and optionally can include a preload of the next image in the direction of the current navigation using the `preloadNextImage` prop (default `true`).

**Comment by steverob** [comment]
@benhowell  thanks a lot for replying.

Sorry for not being clear, when I say viewport, I mean the browser viewport. What I mean by lazy loading is, when I'm showing hundreds of images, I don't want the user to be downloading all those images at the same time. I'd like only the images that are visible in the browser to be downloaded and until then they can remain grey.

Just like this - https://github.com/tuupola/jquery_lazyload

Could you advise me on how to do this please? Thanks.

**Comment by benhowell** [comment]
Ah, I see. 
Currently this is not supported. 

As far as advice, let me see...
You could, for example, add images to the `images` array prop based upon current scroll position of the window, or perhaps change the src attribute of the image in the image array depending on whether or not it's visible according to the scroll position of the window.  

The easiest solution I can think of, off the top of my head would be to monitor your scroll position and change the src of each image in the image array as they're deemed to be in view.

Edit: this is pretty much what I was thinking about: https://stackoverflow.com/a/2322045

The other alternative is to build this into react-grid-gallery and provide a prop such as `enableLazyLoading` but that would require some decent amount of work. PR are always welcome!

Finally, as the gallery display uses thumbnail images, there should be little penalty for greedy loading as they'll be a small file size each.

**Comment by steverob** [comment]
Thank you so much @benhowell. I'll try these things. You rock as a maintainer :) :)

**Comment by Bitha007** [comment]
Is this feature available now._
