### ISSUE TITLE
Customizing the selected state UI

### ISSUE THREAD

**Issue by steverob** [benhowell/react-grid-gallery#51]
Are there options to pass in custom CSV for the selected icon and is it possible to theme the selected state so that I can control the size of the border (grey border that comes when thumbnails are selected) and its color?

**Comment by benhowell** [comment]
Do you mean SVG for the selected icon? Currently there's no way to set a custom icon. 

For styling of the thumbnail and viewport, you can use the following props: `tileViewportStyle` and `thumbnailStyle`. You'll need to be familiar with how it's done internally (see https://github.com/benhowell/react-grid-gallery/blob/master/src/Image.js#L32 and https://github.com/benhowell/react-grid-gallery/blob/master/src/Image.js#L49 and https://github.com/benhowell/react-grid-gallery#programmers-notes).

**Comment by steverob** [comment]
Thank you so much 

--
Regards
Steve Robinson
