### ISSUE TITLE
Call onClickThumbnail() after custom action

### ISSUE THREAD

**Issue by davidfloegel** [benhowell/react-grid-gallery#54]
Hi again,

I'd like to hook into the `onClickThumbnail` method but still run the default after - is that possible?

Something like this:
```javascript
<Gallery onClickThumbnail={(index) => this.incViewCount(index)} />

incViewCount(index) {
   // increase view count in backend

   // open lightbox
}
```

Any help is greatly appreciated!
David

**Comment by benhowell** [comment]
Hi David,
Yes that is possible using the `lightboxWillOpen` function prop. See the docs for more info.
