### ISSUE TITLE
Selection not working on mobile devices

### ISSUE THREAD

**Issue by barrycenter** [benhowell/react-grid-gallery#55]
On a mobile device, tapping the image shows the checkmark overlay to select the thumbnail. However, if an image is tapped and the lightbox displays then the checkmark will never display again and it becomes impossible to select any images in the gallery.

Ideally, one wouldn't need to tap the image twice to select it in any case. Perhaps, an option to always show the checkmark overlay (or just on mobile) is needed?

**Comment by neckaros** [comment]
Maybe long press to select?

**Comment by benhowell** [comment]
Closing due to lack of interest.
