### ISSUE TITLE
Close button off screen on iPad

### ISSUE THREAD

**Issue by barrycenter** [benhowell/react-grid-gallery#56]
When an image is displayed in portrait orientation on an iPad in landscape orientation, the close button is off the screen. This means the lightbox cannot be closed when a portrait image is displayed, perhaps being impossible if the gallery only has portrait images and `backdropClosesModal` is set to false.

**Comment by benhowell** [comment]
Hi Barry,
I don't have an iPad (or any tablet device for that matter) to test this on. I'm tagging this "help wanted" for now.

**Comment by benhowell** [comment]
Image display is handled by (https://github.com/jossmac/react-images)[react-images] so the bug described will be in that library. Closing.
