### ISSUE TITLE
Feature request: Gesture controls on mobile

### ISSUE THREAD

**Issue by barrycenter** [benhowell/react-grid-gallery#58]
It would be nice to have gesture controls, such as pinch-zooming and swiping left and right, within the lightbox on mobile devices. 

As an example, PhotoSwipe http://photoswipe.com/ has these features on a mobile device.

Bonus points if the gestures work on a MacBook with a trackpad as well. :)

**Comment by benhowell** [comment]
Hi Barry,
The lightbox component itself is an upstream library [react-images](https://github.com/jossmac/react-images) and that's where this functionality would need to be implemented. I'd be surprised if there weren't already issues similar to yours already posted.
