### ISSUE TITLE
Component doesn't work properly when inside a modal

### ISSUE THREAD

**Issue by barrydrink** [benhowell/react-grid-gallery#60]
Similar to #37 except I do see the thumbnails the first time the modal opens. However, when new data becomes available and the props are updated, when the modal is reopened there are zero thumbnails, not even the ones that were previously displayed.

I have a put together a minimal app to demonstrate the issue [here](https://bitbucket.org/barry_pnb/react-grid-gallery-test). Initially 2 images are available - click 'Create gallery' to see them. Then click 'Trigger new image data' to simulate a new image becoming available and then reopen the modal.

**Comment by benhowell** [comment]
Can you point me to a live version of the demo please?

**Comment by barrydrink** [comment]
Once I figure out how to do a jsfiddle with multiple components and dependencies, yes :)

**Comment by barrydrink** [comment]
Live version [here](http://react-grid-gallery-test.bitballoon.com/)

**Comment by benhowell** [comment]
It seems to be working fine. I can display the modal with images, close it, hit "trigger new image data" button, open the modal again and the gallery has more images.

What was the behaviour you were expecting?

**Comment by barrydrink** [comment]
The behavious you described is what is meant to happen, but it doesn't work for me. See the second screenshot for what I see after trigger new image data.

What platform and browser did you use? I'm on macOS 10.13.1 and Chrome.

<img width="880" alt="screen shot 2017-11-22 at 09 50 13" src="https://user-images.githubusercontent.com/22638134/33120666-b9f0c31e-cf6a-11e7-9bdf-e71d947acb50.png">
<img width="814" alt="screen shot 2017-11-22 at 09 50 25" src="https://user-images.githubusercontent.com/22638134/33120667-bce15606-cf6a-11e7-8ac0-b1598478316e.png">

**Comment by benhowell** [comment]
Well that's odd. I have tested this particular issue in Firefox, Chromium and Chrome on Linux. I also test on Windows with Edge, Firefox and Chrome and have not seen any issues (although I haven't specifically tested this issue on windows).

Here's what I see (Firefox 57).

![1](https://user-images.githubusercontent.com/1784519/33121374-a15f7738-cfc8-11e7-8865-943fbca17aa9.png)

![2](https://user-images.githubusercontent.com/1784519/33121392-b197c538-cfc8-11e7-93f0-4a0de3edb0d0.png)

I'm going to have to label this as help wanted as I don't have a mac.

**Comment by barrydrink** [comment]
Seems to work ok on Firefox on mac. Safari has the same issue as Chrome though.

**Comment by benhowell** [comment]
As I haven't been able to replicate this issue I'm closing it for the time being.
