### ISSUE TITLE
customOverlay className

### ISSUE THREAD

**Issue by LittleLampLight** [benhowell/react-grid-gallery#61]
https://github.com/benhowell/react-grid-gallery/blob/1a33a0d4bc6139e984db7e85d37dfd7d51432bc9/lib/Image.js#L150

Hello. Is there any reason not to have it in code if i want to rewrite opacity 0 style for example?

**Comment by benhowell** [comment]
Hi, I don't understand your question, can you elaborate?

**Comment by LittleLampLight** [comment]
So point is, that every elemnt has className, but not wrapper for customOverlay. So i can't access it via css and change it's style if i need to.

**Comment by benhowell** [comment]
Fixed in master. :+1:

**Comment by benhowell** [comment]
Realsed in [v0.4.7](https://github.com/benhowell/react-grid-gallery/releases/tag/v0.4.7)
