### ISSUE TITLE
add a new prop

### ISSUE THREAD

**Issue by theITed** [benhowell/react-grid-gallery#65]
is it possible on adding a new prop to each image? 
for example, I would like not to use LightBox, and add a href element on each image. 

I've added a href proprty in the document
```
  {
          src: "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_b.jpg",
          thumbnail: "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_n.jpg",
          thumbnailWidth: 320,
          thumbnailHeight: 174,
          isSelected: false,
          caption: "After Rain (Jeshu John - designerspics.com)",
          href: "https://google.ro",
        },
```

Then I am accessing the href property, but without success:
```
    const imgMap = IMAGES.map((data) => data.href);
    console.log(imgMap); //this works.
```
this does not: //href is not displayed
`
  <Gallery images={IMAGES} enableLightbox={false} href={imgMap} />
`

**Comment by benhowell** [comment]
No, it's not possible to arbitrarily add your own props. To do something custom when clicking on a thumbnail, you will need to provide a custom function with the `onClickThumbnail` prop.
