### ISSUE TITLE
images orientation is changed

### ISSUE THREAD

**Issue by mis94** [benhowell/react-grid-gallery#66]
In the first screenshot I have some images with low quality but equal dimentions (width & height)
<img width="950" alt="capture" src="https://user-images.githubusercontent.com/6617388/35039047-5b106592-fb85-11e7-8bc1-c51b7d225716.PNG">

however, in the second screenshot I have the same images with higher quality but some of the images have non-equal dimensions, the problem is that their orientation is changed and they seem to be rotated
<img width="949" alt="capture3" src="https://user-images.githubusercontent.com/6617388/35039146-a368b7a4-fb85-11e7-925e-8f222348b1fd.PNG">

Is there anything I can do to fix this problem?

**Comment by benhowell** [comment]
Image orientation isn't changed by react-grid-gallery so I'd be checking the exif orientation property on your high res photos.

**Comment by mis94** [comment]
OK, I've checked the orientation of the rotated images and found that they are different (equal 6) from other images (equal 1).....what can I do to make react-grid-gallery display them properly?

**Comment by benhowell** [comment]
react-grid-gallery is displaying them properly. Orientation 1 is what all your images should be. Orientation 6 is rotated in some way. You'll need to rotate your photos (i.e. set orientation to 1) which you can do using pretty much any image viewer out there.

If you need to rotate your images in code (e.g. if you have no control over the images, as in, others are uploading in a web app you've built or something), then I'd recommend using https://github.com/exif-js/exif-js for determining rotation and then loading the image into a canvas element and performing the appropriate transformation and then turning it back into an image with the correct rotation. I have written code that does this but it's clojurescript so pasting an example here wouldn't help you.

See http://jpegclub.org/exif_orientation.html to get an understanding of EXIF rotation.

**Comment by mis94** [comment]
@benhowell thank for your response. Your comment about using the exif orientation property gave me a great hint solving my problem. I've made an edit in thumbnailStyle method in Image class to do this rotation from react-grid-gallery and I've created a pull request.
