### ISSUE TITLE
HelpWanted: Display custom tooltip on image select 

### ISSUE THREAD

**Issue by vignesh-almond** [benhowell/react-grid-gallery#68]
Is it possible to display a custom tool tip when the image is selected ?

**Comment by benhowell** [comment]
The `caption` prop sets the tooltip.

**Comment by vignesh-almond** [comment]
But that can only be a string right ?. I want to add something like this https://github.com/romainberger/react-portal-tooltip when the image is selected ? 
A tooltip or bubble to be shown when the image is selected. Is is possible to do something like this ?

**Comment by benhowell** [comment]
That's right, it can only be a string. It isn't possible to do anything other than a string as a caption. You could use the `customOverlay` prop instead. [See this demo](https://benhowell.github.io/react-grid-gallery/#custom-overlay)
