### ISSUE TITLE
Cannot read property 'complete' of undefined

### ISSUE THREAD

**Issue by Aathi** [benhowell/react-grid-gallery#69]
HI, @benhowell 
My `images` array has 32  images. Lightbox works perfectly with only few images after it throws below  error. 
<img width="979" alt="casuarina_tree_-_the_contemporary_bar_and_restaurant" src="https://user-images.githubusercontent.com/5355180/36458699-77fb1d3c-16b0-11e8-82cc-f6c5ed894c52.png">

**Comment by benhowell** [comment]
This is a recently introduced [bug in react-images](https://github.com/jossmac/react-images/issues/201). This bug has been fixed and will be released in the next version of [react-images](https://github.com/jossmac/react-images).
