### ISSUE TITLE
onClick listener and onTouchEnd

### ISSUE THREAD

**Issue by linx1stargazer** [benhowell/react-grid-gallery#70]
### Expected behaviour
open and close image when you click on without errors

### Actual behaviour
When ever you click on the image to enlarge i receive:
proxyConsole.js:54 Warning: Expected `onClick` listener to be a function, instead got `false`.

If you used to conditionally omit it with onClick={condition && value}, pass onClick={condition ? value : undefined} instead.
    in div (created by Container)
    in Container (created by Lightbox)
    in CSSTransitionGroupChild (created by TransitionGroup)
    in div (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup
    in div
    in PassContext
If you used to conditionally omit it with onTouchEnd={condition && value}, pass onTouchEnd={condition ? value : undefined} instead.
    in div (created by Container)
    in Container (created by Lightbox)
    in CSSTransitionGroupChild (created by TransitionGroup)
    in div (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup
    in div
    in PassContext

### Operating system
windows 10

### Browser and version
chrome

**Comment by benhowell** [comment]
proxyConsole.js is not part of [react-grid-gallery](https://github.com/benhowell/react-grid-gallery)
