### ISSUE TITLE
Browser Error when importing component: "TypeError: Cannot read property 'isRequired' of undefined"

### ISSUE THREAD

**Issue by MRMTC** [benhowell/react-grid-gallery#72]
### Expected behaviour
Use the code from the following link: https://www.npmjs.com/package/react-grid-gallery#quick-and-dirty-start to implement the component in my project.

### Actual behaviour
When trying to compile the project, I get the error seen below:

![image](https://user-images.githubusercontent.com/26508189/38168495-0505d706-354e-11e8-9d65-fa4c46917fb3.png)

### Steps to reproduce behaviour
The code below causes the issue.  It was noted that the error occurs as soon as the "import Gallery from 'react-grid-gallery';" line is called i.e. if all other code is removed, this line causes the program to return the error.  Issue seems to be related to the "prop types", but I am passing through all the values (to my knowledge).

`import React from 'react';
import { render } from 'react-dom';
import Gallery from 'react-grid-gallery';

// Image Imports
	import img1 from '../../pictures/1.jpg';
	import img2 from '../../pictures/2.jpg';
	import img3 from '../../pictures/3.jpg';

const IMAGES =
[{
        src: img1,
        thumbnail: img1,
        thumbnailWidth: 320,
        thumbnailHeight: 174,
        isSelected: true,
        caption: "After Rain (Jeshu John - designerspics.com)"
},
{
        src: img2,
        thumbnail: img2,
        thumbnailWidth: 320,
        thumbnailHeight: 212,
        tags: [{value: "Ocean", title: "Ocean"}, {value: "People", title: "People"}],
        caption: "Boats (Jeshu John - designerspics.com)"
},
 
{
        src: img3,
        thumbnail: img3,
        thumbnailWidth: 320,
        thumbnailHeight: 212
}]

const PhotoGallery = () => {

	return (
				<div className="PhotoGallery">
		            <Gallery images={IMAGES}/>
		        </div>
	)//end return

}//end Photos

export default PhotoGallery;`

### Operating system
Windows 10 Enterprise

### Browser and version
Google Chrome Version: Version 65.0.3325.181 (Official Build) (64-bit)

### Hardware
![image](https://user-images.githubusercontent.com/26508189/38168508-63ad147c-354e-11e8-9be1-011c85f7e1b3.png)

Please let me know if you need any further information in order to assist.

Thanks.

**Comment by benhowell** [comment]
(react-grid-gallery)[https://github.com/benhowell/react-grid-gallery] does not contain any reference to cssTransitionGroupChild.css so your error must be coming from elsewhere. Perhaps it's related to something in (react-images)[https://github.com/jossmac/react-images] but I can't see any issue like the one you've mentioned. As can be seen on the (demo page)[https://benhowell.github.io/react-grid-gallery/] (running latest release), there are no errors.

**Comment by MRMTC** [comment]
Thanks @benhowell.  Will have a look and let you know if I don't come right.
