### ISSUE TITLE
thumbnailWidth` is marked as required

### ISSUE THREAD

**Issue by interpegasus** [benhowell/react-grid-gallery#74]
### Expected behaviour
 Thank you for this awesome npm package. I would like to know what options can be passed to  the Gallery; And how to create a gallery without specifying "thumbnailWidth".

### Actual behaviour
Console reports error: 
`thumbnailWidth is marked as required`

### Steps to reproduce behaviour
```
 this.props.images.forEach(function(object) {
      images.push({
        src: object.url_full,
        thumbnail: object.url_thumb,
        thumbnailWidth: null,
        thumbnailHeight: null
      });
    });
```

```
              <div className="sixteen wide column">
                <h1>Gallery</h1>
                <Gallery images={images} />
              </div>
```

### Operating system
macOS High Sierra

### Browser and version
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

### Hardware
MacBook

**Comment by benhowell** [comment]
thumbnailWidth is required as stated in the README.

see: https://github.com/benhowell/react-grid-gallery#image-options
and https://github.com/benhowell/react-grid-gallery#programmers-notes
