### ISSUE TITLE
Alt Attribute

### ISSUE THREAD

**Issue by interpegasus** [benhowell/react-grid-gallery#75]
### Expected behaviour
Hi, The image tag takes an alt attribute. I would like to know how to pass the "alt" to each image in the gallery. Thanks again. Regards.

### Actual behaviour
There is a warning in the console about the missing "alt" attribute

### Operating system
Mac OS High Sierra
### Browser and version
Chrome Version 66.0.3359.117 (Official Build) (64-bit)

### Hardware
Macbook

**Comment by benhowell** [comment]
Thanks for the report!

Fixed in [v0.4.9](https://github.com/benhowell/react-grid-gallery/releases/tag/v0.4.9) :+1:
