### ISSUE TITLE
backdropClosesModal

### ISSUE THREAD

**Issue by ScottMRafferty** [benhowell/react-grid-gallery#79]
Hi Ben,

Might be an issue.  Not sure.  Getting an error when viewing Lightbox on these 2 lines since I moved to React 16.  By specifying the backdropClosesModal prop on Gallery the errors disappear.  Complaining about the prop being false as opposed to a function?  I've got a ton on at the moment so specifying the property is good enough for me right now.

Lightbox.js
229 onClick={backdropClosesModal && this.closeBackdrop}
230 onTouchEnd={backdropClosesModal && this.closeBackdrop}

### Expected behaviour
Not specifying the backdropClosesModal property for Gallery should not produce errors when viewing Lightbox.
### Actual behaviour
Not specifying the backdropClosesModal property throws an error when opening and closing the Lightbox.

### Steps to reproduce behaviour
Omit the backdropClosesModal property (and I assume the closeBackdrop property as well) from Gallery.

**Comment by benhowell** [comment]
Thanks Scott,
Strange error. The prop is supposed to be a boolean so I'm not sure what's going on. The code looks ok to me so I'll have to spend some time testing with react 16 to figure it out.

**Comment by benhowell** [comment]
Thanks Scott. Looks like it's a problem in an upstream library: https://github.com/jossmac/react-images (which provides the lightbox component), specifically https://github.com/jossmac/react-images/blob/a99a878b38623e7e71325e3f07f2425dc46bb85a/src/Lightbox.js#L229 and https://github.com/jossmac/react-images/blob/a99a878b38623e7e71325e3f07f2425dc46bb85a/src/Lightbox.js#L230

Looking further into it, the current release of react-images (0.5.16) is not ready for React 16 yet. Closing this issue for now and creating an issue in react-images.

**Comment by ScottMRafferty** [comment]
Cheers Ben.
