### ISSUE TITLE
Compile error on shuffleArray

### ISSUE THREAD

**Issue by ruegreen** [benhowell/react-grid-gallery#80]
Using your example code I cannot get shuffleArray to resolve.  Is this defined somewhere in your repo or ?

**Comment by benhowell** [comment]
See #48 and #13

**Comment by ruegreen** [comment]
You simple one works but all hell breaks loose using your example with the array being defined as default props for the component.  I will work with the simple one for now, not sure whats going on with the other one, technically I should be able to send the array from the “down and dirty” example to the more robust code that you have for selection, etc.

I was looking for the effect of the simple example but the thumbnail nav on the bottom of the example you linked, will jack around with it and see if Ic can make some ground on what the problem is.

Thanks again!

-Rue

**Comment by benhowell** [comment]
I don't understand what you mean. The examples on the demo page cover most functionality. The code for the examples is here: https://github.com/benhowell/react-grid-gallery/tree/master/examples and the arrays passed to those examples are in the code for each.

**Comment by ruegreen** [comment]
This code from “Quick and Dirty Start” works when I move the code to my project, with no issues. Look here: https://benhowell.github.io/react-grid-gallery/#demo and scroll down to your Quick and Dirty snap shot..thats what I am referring too…

import React from 'react';
import { render } from 'react-dom';
import Gallery from 'react-grid-gallery';

const IMAGES =
[{
        src: "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_b.jpg",
        thumbnail: "https://c2.staticflickr.com/9/8817/28973449265_07e3aa5d2e_n.jpg",
        thumbnailWidth: 320,
        thumbnailHeight: 174,
        isSelected: true,
        caption: "After Rain (Jeshu John - designerspics.com)"
},
{
        src: "https://c2.staticflickr.com/9/8356/28897120681_3b2c0f43e0_b.jpg",
        thumbnail: "https://c2.staticflickr.com/9/8356/28897120681_3b2c0f43e0_n.jpg",
        thumbnailWidth: 320,
        thumbnailHeight: 212,
        tags: [{value: "Ocean", title: "Ocean"}, {value: "People", title: "People"}],
        caption: "Boats (Jeshu John - designerspics.com)"
},

{
        src: "https://c4.staticflickr.com/9/8887/28897124891_98c4fdd82b_b.jpg",
        thumbnail: "https://c4.staticflickr.com/9/8887/28897124891_98c4fdd82b_n.jpg",
        thumbnailWidth: 320,
        thumbnailHeight: 212
}]

render(
        <Gallery images={IMAGES}/>,
        document.getElementById('example-0')
);

Your other demos do not use a  const Images array to pass the images into the samples, they use default props images defined as an array.  There is something not working with that method of the array and the code.  Not sure if I am missing any modules or that my updated modules are not partying with your code.

I am attempting to take your examples and move them into my reactjs project and for some odd reason any sample you provide other than the one I just listed above, I get an error in your Gallery.js file.  The only difference I see is how the array is built, shuffled and consumed…  It may have nothing to do with the array but strange that I can use the same code from you project and the sample above works like a charm..

-Rue
