### ISSUE TITLE
Thumbnails can't be viewed in their default aspect ratio

### ISSUE THREAD

**Issue by DhawalRank** [benhowell/react-grid-gallery#81]
### Expected behaviour
View thumbnails in their default aspect ratio
### Actual behaviour
thumbnail height and width are required. So all thumbnails become of the same aspect ratio which drags portrait images wide.
### Steps to reproduce behaviour
Get images from an api whose aspect ratios are different
### Operating system
All
### Browser and version
All

**Comment by benhowell** [comment]
If you take a look at the examples: https://benhowell.github.io/react-grid-gallery/ and their code: https://github.com/benhowell/react-grid-gallery/tree/master/examples you can see there are many examples of portrait images on display.

**Comment by DhawalRank** [comment]
Yes, but they require thumbnailWidth and thumbnailHeight to be passed to the component. If set height and width to 0, it works as I want it to but the console is giving me a warning that width cant bt NaN. I completely understand what is the problem. One solution might be to have thumbnailHeight and thumbnailWidth accept 0 and display the original image size when that happens. By this, your current use case remains intact with an extra feature added.

**Comment by benhowell** [comment]
Thumbnails need their height to be set to `rowHeight` (to render uniform row) and this is why thumbnails are scaled.
