### ISSUE TITLE
[question] How do people support large galleries? Any future possibility of lazy loading?

### ISSUE THREAD

**Issue by clbarrell** [benhowell/react-grid-gallery#82]
Hello,

I'm using this component with a gallery that needs to be be able to handle large amounts of photos - such as ~1000. 

Do you have any plans on implementing lazy loading so that all gallery images don't load at once?

Alternatively, do you know how others are approaching this problem?

Thanks

**Comment by benhowell** [comment]
I implement dynamic loading of images by changing the contents of the images prop from within whatever component or app I'm using to push images into react-grid-gallery. Loading of images is achieved by changing the images prop and therefore any lazy or dynamic loading logic needs to be implemented outside the react-grid-gallery component.

**Comment by clbarrell** [comment]
Thanks Ben, appreciate it
