### ISSUE TITLE
Feature request: custom http headers, i.e. authorization header

### ISSUE THREAD

**Issue by ByteCrunch** [benhowell/react-grid-gallery#85]
I have no issue so far and react-grid-gallery is great.
One thing I would like to have is to pass custom headers, in my case an Authorization header. Is there any way to do this at the moment (without forking the project and do custom code) ?

If this is not the right place for this kind of inquiry, please delete the issue.

Kind regards,
ByteCrunch

**Comment by benhowell** [comment]
Hi @ByteCrunch, I'm not sure what you mean re: Authorization header. Can you give me an example?

**Comment by ByteCrunch** [comment]
You can send an authorization token, i.e. for JWT, within your request in the http headers.
For specifications of the authorization header, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization

An example with axioms would be:
fetch('URL', { 
   method: 'get', 
   headers: new Headers({
     'Authorization': 'Bearer 01234567890ABCDEF')
   }), 
   body: ...
 });

I‘m writing from my mobile and from vacation, please forgive any typos.

Greetings, ByteCrunch

**Comment by benhowell** [comment]
I understand what authorization headers are, can you give me an example of how you want to use them with react-grid-gallery? Do you want to use authorization on the src and thumbnail URL's?

**Comment by ByteCrunch** [comment]
Yes, correct, I want to use the header for src and thumbnail URLs. I guess a global option would be nice, maybe an option to set a state containing the headers information which should be inserted to every http request. Like:
{ Authorization: “Bearer ...” }
so it doesn’t have to be set for every image repeatedly.

Kind regards,
ByteCrunch

**Comment by benhowell** [comment]
Sounds like a useful feature.

**Comment by itoldya** [comment]
Hi @ByteCrunch! 

Is it still actual for you? It seems to be a really rare use case. 

As a workaround, you can use Service Worker to intercept the img fetchs and add custom headers https://www.sjoerdlangkemper.nl/2021/01/06/adding-headers-to-image-request-using-service-workers/.

I close the issue for now because it's not the responsibility of the library to do such things.
