### ISSUE TITLE
Warning: Expected 'onClick' listener

### ISSUE THREAD

**Issue by StevenHensgen** [benhowell/react-grid-gallery#88]
If you set the Gallery enableImageSelection to false when a user clicks on an image there will be two warning messages thrown inside dev tools.

`Warning: Expected onClick listener to be a function, instead got false.

If you used to conditionally omit it with onClick={condition && value}, pass onClick={condition ? value : undefined} instead.
    in div (created by Container)
    in Container (created by Lightbox)
    in Transition (created by CSSTransition)
    in CSSTransition
    in div (created by TransitionGroup)
    in TransitionGroup
    in div
    in PassContext`

`Warning: Expected onTouchEnd listener to be a function, instead got false.

If you used to conditionally omit it with onTouchEnd={condition && value}, pass onTouchEnd={condition ? value : undefined} instead.
    in div (created by Container)
    in Container (created by Lightbox)
    in Transition (created by CSSTransition)
    in CSSTransition
    in div (created by TransitionGroup)
    in TransitionGroup
    in div
    in PassContext`

enabling the image selection will remove this issue.

**Comment by benhowell** [comment]
see https://github.com/benhowell/react-grid-gallery/issues/83
