### ISSUE TITLE
How do i customize the checkbox in gallery?

### ISSUE THREAD

**Issue by aniketparab4** [benhowell/react-grid-gallery#90]
I am not able to customize the checkbox in gallery component.

**Comment by benhowell** [comment]
By replacing the [checkbutton](https://github.com/benhowell/react-grid-gallery/blob/master/src/CheckButton.js) with your own

**Comment by aniketparab4** [comment]
Then I have make the changes in node_module which i want to avoid. Please can you set the styling of checkbox as props, so we may able to pass the desired css classname from parent. And we easily able to customize the checkbox

**Comment by benhowell** [comment]
If you make a pull request I'd be happy to take a look.
