### ISSUE TITLE
Update dependencies for React 16

### ISSUE THREAD

**Issue by johnantoni** [benhowell/react-grid-gallery#92]
Hi, any news on updating dependencies for React 16?

Just getting "unmet dependency for react-grid-gallery" for React 15 that would be great to clean out.

I've been running the library in 16.3 for about 6 months with no problem so probably safe to assume it's good but best for the author to check it out.

Thanks in advance,

**Comment by itoldya** [comment]
Hello @johnantoni! Thanks for reporting!

I'm proud to say that we've finally updated to dependencies React 16 and released [v0.5.6](https://github.com/benhowell/react-grid-gallery/releases/tag/v0.5.6) 😀. So I'm closing this issue.

To be serious I am aware that the current react version is 18. We have some problems with the upgrade on this version so we are considering workarounds in [this discussion](https://github.com/benhowell/react-grid-gallery/discussions/179). Please feel free to join.
