### ISSUE TITLE
React Grid Disappears when integrating a container with a nested row div in bootstrap

### ISSUE THREAD

**Issue by ryj1023** [benhowell/react-grid-gallery#96]
I am trying to make sure the div I am wrapping the grid with is the same width as the div above it. When Bootstrap is introduced and the Grid is wrapped in a "container" div nested with a "row" div, the entire grid disappears. It doesn't even seem to register with the DOM. Any particular reason for this behavior? And is there a workaround?

https://codesandbox.io/s/ll2vxmqnql

**Comment by benhowell** [comment]
All the extra code and markup injected by CodeSandbox or whatever it is certainly confuses the issue. There are a number of reasons why this wasn't working. First, you need to mount your galleries in separate dom elements and second, the element you're mounting them in must first be already mounted, and second, have a width.

I suggest looking at the examples folder (which generates the demo page) for a good design for creating multiple galleries in a single page.

I've hacked the "CodeBox" to demonstrate how to fix your issues with regards to mounting.

https://codesandbox.io/s/3q96138pnm

**Comment by ryj1023** [comment]
I've determined that the bug is that the Gallery component can not be placed in a div with "display: flex"

To demonstrate the bug in a more streamlined way, I've removed bootstrap from the example and added display: flex; to the .App selectory.

You will see that the gallery is not presented in a div that has the "App" class.

```
.App {
  font-family: sans-serif;
  text-align: center;
  display: flex;
}
```

https://codesandbox.io/s/0q7olvy99l

**Comment by benhowell** [comment]
As far as I can see, gallery2 is rendering in the same position as gallery1. Here's gallery2 without gallery 1: https://codesandbox.io/s/vvln2rpvxy

**Comment by ryj1023** [comment]
I intentionally stripped down the example in order to eliminate as much complexity as possible.

This codesandbox is not our actual use-case. Our actual use case places the gallery into a Bootstrap 4 grid (which uses the flexbox model for layout).

Bootstrap 4 is incredibly popular, as is the flex box model for modern css layouts.

https://getbootstrap.com/docs/4.0/layout/grid/

Something is preventing this component from functioning when it is placed in an element with display:flex.

This problem, prevents it from being usable in a default Bootstrap 4 grid and presumably a large amount of other css frameworks.

https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by ryj1023** [comment]
Thank you for you assistance. After reviewing bootstrap's grid model I realized that the content should be placed in a "column" (e.g., "col-sm")

After placing your component in the appropriate div structure, it renders fine.

https://codesandbox.io/s/4j5j8mzw5x

**Comment by benhowell** [comment]
> Something is preventing this component from functioning when it is placed in an element with display:flex.

I'm glad you have this working now, however, I must reiterate that react-grid-gallery works fine in a flexbox layout. I have been using it in a flex layout ever since I started the project.

**Comment by Keshavdulal** [comment]
I also came across this weird issue.
I was placing Gallery component inside a flex container rendering one additional dynamic component inside the same flexbox.
I had to use @ryj1023 solution to fix the issue.
