### ISSUE TITLE
Feature suggestion: lightboxWillOpen determines if light box should open

### ISSUE THREAD

**Issue by olgeorge** [benhowell/react-grid-gallery#98]
### Expected behaviour

I have a gallery with images, videos and folders. I'd like the lightbox to open for images, for videos I'd like to open my own lightbox, for folders I'd like to redirect.

### Actual behaviour

There's no way to control whether the light box will open for a certain image (either open for all or open for none)

I just want an `if` statement here
https://github.com/benhowell/react-grid-gallery/blob/master/src/Gallery.js#L63

**Comment by benhowell** [comment]
Can you make a pull request with the changes you want along with a demo example and some docs in the readme?
