### ISSUE TITLE
Could not find a declaration file for module 'react-grid-gallery'

### ISSUE THREAD

**Issue by nickwild-999** [benhowell/react-grid-gallery#99]
### Throws the above error and suggest creating an .d.ts file

Any thoughts as to how to resolve this -  this has happened on a few packages with Gatsby

**Comment by benhowell** [comment]
Sorry, I don't know anything about Gatsby.

**Comment by uragecz** [comment]
It's not about Gatsby, if you are using Typescript the project needs to have .d.ts file with declared module and its types.. So it's definitely fault / lack of this project.. Usually bigger projects use Typescript... Soo this should be fixed / added.

**Comment by benhowell** [comment]
Sorry, I don't know anything about Typescript.
